### ISSUE TITLE
[FEAT] 10월 3주차 스포티 개발

### ISSUE THREAD

**Issue by mini-min** [mini-min/Spo-T_iOS#1]
# 👀 이슈 (issue)

10.11(월)~10.16(토)까지 수행할 개발 내용들입니다.

# 🚀 to-do

☑️ 프로젝트 기본 세팅
- [x] PR, 이슈 템플릿 생성
- [x] 새 프로젝트 추가
- [x] cocoapods 라이브러리 추가
- [x] 폴더링 세팅
- [x] 시작하는 뷰컨 변경 코드 추가
- [x] SwiftLint 추가
- [x] .gitignore 추가

☑️ Extension
- [x] UIView+Extension 추가
- [x] UIColor+Extension 추가

☑️ 뷰 구현
- [x] 로그인 뷰
- [x] 회원가입 뷰
- [x] 커스텀 탭바 뷰

☑️ 기능 구현
- [x] 탭바 컨트롤러 뷰컨 연결
